/* tslint:disable */
/* eslint-disable */
/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PaymentCustomer } from '../models';
// @ts-ignore
import { PaymentcustomersCreateCustomerResponse } from '../models';
// @ts-ignore
import { PaymentcustomersListAllResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * PaymentCustomersApi - axios parameter creator
 * @export
 */
export const PaymentCustomersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a Payment Customer
         * @summary Create a Payment Customer
         * @param {PaymentCustomer} [paymentCustomer] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCustomer: async (paymentCustomer?: PaymentCustomer, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/payment-customers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: paymentCustomer,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/payment-customers',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(paymentCustomer, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a payment customer by ID.
         * @summary Retrieve a Payment Customer
         * @param {string} paymentCustomerId The ID of the payment customer
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById: async (paymentCustomerId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paymentCustomerId' is not null or undefined
            assertParamExists('getById', 'paymentCustomerId', paymentCustomerId)
            const localVarPath = `/v2/payment-customers/{payment_customer_id}`
                .replace(`{${"payment_customer_id"}}`, encodeURIComponent(String(paymentCustomerId !== undefined ? paymentCustomerId : `-payment_customer_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/payment-customers/{payment_customer_id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List all payment customers
         * @summary List all Payment Customers
         * @param {string} [limit] A limit on the number of objects to be returned, between 1 and 100.
         * @param {string} [startingAfter] A cursor for use in pagination. &#x60;starting_after&#x60; is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with &#x60;aaa&#x60;, your subsequent call can include &#x60;starting_after&#x60;&#x3D;&#x60;aaa&#x60; in order to fetch the next page of the list.
         * @param {string} [endingBefore] A cursor for use in pagination. &#x60;ending_before&#x60; is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with &#x60;aaa&#x60;, your subsequent call can include &#x60;ending_before&#x60;&#x3D;&#x60;aaa&#x60; in order to fetch the previous page of the list.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAll: async (limit?: string, startingAfter?: string, endingBefore?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/payment-customers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)
            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (startingAfter !== undefined) {
                localVarQueryParameter['starting_after'] = startingAfter;
            }

            if (endingBefore !== undefined) {
                localVarQueryParameter['ending_before'] = endingBefore;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/payment-customers',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentCustomersApi - functional programming interface
 * @export
 */
export const PaymentCustomersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaymentCustomersApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a Payment Customer
         * @summary Create a Payment Customer
         * @param {PaymentCustomersApiCreateCustomerRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCustomer(requestParameters: PaymentCustomersApiCreateCustomerRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentcustomersCreateCustomerResponse>> {
            const paymentCustomer: PaymentCustomer = {
                id: requestParameters.id,
                user_id: requestParameters.user_id,
                email: requestParameters.email,
                country_code: requestParameters.country_code,
                phone_number: requestParameters.phone_number,
                first_name: requestParameters.first_name,
                middle_name: requestParameters.middle_name,
                last_name: requestParameters.last_name,
                metadata: requestParameters.metadata,
                created: requestParameters.created,
                updated: requestParameters.updated
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCustomer(paymentCustomer, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get a payment customer by ID.
         * @summary Retrieve a Payment Customer
         * @param {PaymentCustomersApiGetByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getById(requestParameters: PaymentCustomersApiGetByIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentCustomer>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getById(requestParameters.paymentCustomerId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * List all payment customers
         * @summary List all Payment Customers
         * @param {PaymentCustomersApiListAllRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAll(requestParameters: PaymentCustomersApiListAllRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentcustomersListAllResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAll(requestParameters.limit, requestParameters.startingAfter, requestParameters.endingBefore, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PaymentCustomersApi - factory interface
 * @export
 */
export const PaymentCustomersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaymentCustomersApiFp(configuration)
    return {
        /**
         * Create a Payment Customer
         * @summary Create a Payment Customer
         * @param {PaymentCustomersApiCreateCustomerRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCustomer(requestParameters: PaymentCustomersApiCreateCustomerRequest = {}, options?: AxiosRequestConfig): AxiosPromise<PaymentcustomersCreateCustomerResponse> {
            return localVarFp.createCustomer(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a payment customer by ID.
         * @summary Retrieve a Payment Customer
         * @param {PaymentCustomersApiGetByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById(requestParameters: PaymentCustomersApiGetByIdRequest, options?: AxiosRequestConfig): AxiosPromise<PaymentCustomer> {
            return localVarFp.getById(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * List all payment customers
         * @summary List all Payment Customers
         * @param {PaymentCustomersApiListAllRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAll(requestParameters: PaymentCustomersApiListAllRequest = {}, options?: AxiosRequestConfig): AxiosPromise<PaymentcustomersListAllResponse> {
            return localVarFp.listAll(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createCustomer operation in PaymentCustomersApi.
 * @export
 * @interface PaymentCustomersApiCreateCustomerRequest
 */
export type PaymentCustomersApiCreateCustomerRequest = {
    
} & PaymentCustomer

/**
 * Request parameters for getById operation in PaymentCustomersApi.
 * @export
 * @interface PaymentCustomersApiGetByIdRequest
 */
export type PaymentCustomersApiGetByIdRequest = {
    
    /**
    * The ID of the payment customer
    * @type {string}
    * @memberof PaymentCustomersApiGetById
    */
    readonly paymentCustomerId: string
    
}

/**
 * Request parameters for listAll operation in PaymentCustomersApi.
 * @export
 * @interface PaymentCustomersApiListAllRequest
 */
export type PaymentCustomersApiListAllRequest = {
    
    /**
    * A limit on the number of objects to be returned, between 1 and 100.
    * @type {string}
    * @memberof PaymentCustomersApiListAll
    */
    readonly limit?: string
    
    /**
    * A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `aaa`, your subsequent call can include `starting_after`=`aaa` in order to fetch the next page of the list.
    * @type {string}
    * @memberof PaymentCustomersApiListAll
    */
    readonly startingAfter?: string
    
    /**
    * A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `aaa`, your subsequent call can include `ending_before`=`aaa` in order to fetch the previous page of the list.
    * @type {string}
    * @memberof PaymentCustomersApiListAll
    */
    readonly endingBefore?: string
    
}

/**
 * PaymentCustomersApiGenerated - object-oriented interface
 * @export
 * @class PaymentCustomersApiGenerated
 * @extends {BaseAPI}
 */
export class PaymentCustomersApiGenerated extends BaseAPI {
    /**
     * Create a Payment Customer
     * @summary Create a Payment Customer
     * @param {PaymentCustomersApiCreateCustomerRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentCustomersApiGenerated
     */
    public createCustomer(requestParameters: PaymentCustomersApiCreateCustomerRequest = {}, options?: AxiosRequestConfig) {
        return PaymentCustomersApiFp(this.configuration).createCustomer(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a payment customer by ID.
     * @summary Retrieve a Payment Customer
     * @param {PaymentCustomersApiGetByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentCustomersApiGenerated
     */
    public getById(requestParameters: PaymentCustomersApiGetByIdRequest, options?: AxiosRequestConfig) {
        return PaymentCustomersApiFp(this.configuration).getById(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List all payment customers
     * @summary List all Payment Customers
     * @param {PaymentCustomersApiListAllRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentCustomersApiGenerated
     */
    public listAll(requestParameters: PaymentCustomersApiListAllRequest = {}, options?: AxiosRequestConfig) {
        return PaymentCustomersApiFp(this.configuration).listAll(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
