/* tslint:disable */
/* eslint-disable */
/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { Transfer } from '../models';
// @ts-ignore
import { TransfersCreateOrganizationTransferRequest } from '../models';
// @ts-ignore
import { TransfersCreateTransferRequest } from '../models';
// @ts-ignore
import { TransfersGetAllResponse } from '../models';
// @ts-ignore
import { TransfersListAllResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * TransfersApi - axios parameter creator
 * @export
 */
export const TransfersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a transfer for the organization\'s wallet to an api app.
         * @summary Create an Organization Transfer
         * @param {TransfersCreateOrganizationTransferRequest} [transfersCreateOrganizationTransferRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrganizationTransfer: async (transfersCreateOrganizationTransferRequest?: TransfersCreateOrganizationTransferRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/organization-transfers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: transfersCreateOrganizationTransferRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/organization-transfers',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(transfersCreateOrganizationTransferRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a transfer.
         * @summary Create a Transfer
         * @param {TransfersCreateTransferRequest} [transfersCreateTransferRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTransfer: async (transfersCreateTransferRequest?: TransfersCreateTransferRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/transfers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: transfersCreateTransferRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/transfers',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(transfersCreateTransferRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List all transfers to and from an Organization\'s wallet.
         * @summary List all Organization Transfers
         * @param {number} [limit] A limit on the number of objects to be returned, between 1 and 100.
         * @param {string} [startingAfter] A cursor for use in pagination. &#x60;starting_after&#x60; is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with &#x60;aaa&#x60;, your subsequent call can include &#x60;starting_after&#x60;&#x3D;&#x60;aaa&#x60; in order to fetch the next page of the list.
         * @param {string} [endingBefore] A cursor for use in pagination. &#x60;ending_before&#x60; is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with &#x60;aaa&#x60;, your subsequent call can include &#x60;ending_before&#x60;&#x3D;&#x60;aaa&#x60; in order to fetch the previous page of the list.
         * @param {string} [userId] Include only results with this user ID attached.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAll: async (limit?: number, startingAfter?: string, endingBefore?: string, userId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/organization-transfers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)
            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (startingAfter !== undefined) {
                localVarQueryParameter['starting_after'] = startingAfter;
            }

            if (endingBefore !== undefined) {
                localVarQueryParameter['ending_before'] = endingBefore;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/organization-transfers',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a transfer by its id.
         * @summary Get a Transfer
         * @param {string} transferId Id of the transfer to fetch
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById: async (transferId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'transferId' is not null or undefined
            assertParamExists('getById', 'transferId', transferId)
            const localVarPath = `/v2/transfers/{transfer_id}`
                .replace(`{${"transfer_id"}}`, encodeURIComponent(String(transferId !== undefined ? transferId : `-transfer_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/transfers/{transfer_id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a transfer by its id.
         * @summary Get a Transfer
         * @param {string} transferId ID of the transfer to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById_1: async (transferId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'transferId' is not null or undefined
            assertParamExists('getById_1', 'transferId', transferId)
            const localVarPath = `/v2/organization-transfers/{transfer_id}`
                .replace(`{${"transfer_id"}}`, encodeURIComponent(String(transferId !== undefined ? transferId : `-transfer_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/organization-transfers/{transfer_id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List all transfers.
         * @summary List all Transfers
         * @param {number} [limit] A limit on the number of objects to be returned, between 1 and 100.
         * @param {string} [startingAfter] A cursor for use in pagination. &#x60;starting_after&#x60; is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with &#x60;aaa&#x60;, your subsequent call can include &#x60;starting_after&#x60;&#x3D;&#x60;aaa&#x60; in order to fetch the next page of the list.
         * @param {string} [endingBefore] A cursor for use in pagination. &#x60;ending_before&#x60; is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with &#x60;aaa&#x60;, your subsequent call can include &#x60;ending_before&#x60;&#x3D;&#x60;aaa&#x60; in order to fetch the previous page of the list.
         * @param {string} [userId] Include only results with this user ID attached.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAll: async (limit?: number, startingAfter?: string, endingBefore?: string, userId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/transfers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)
            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (startingAfter !== undefined) {
                localVarQueryParameter['starting_after'] = startingAfter;
            }

            if (endingBefore !== undefined) {
                localVarQueryParameter['ending_before'] = endingBefore;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v2/transfers',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransfersApi - functional programming interface
 * @export
 */
export const TransfersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransfersApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a transfer for the organization\'s wallet to an api app.
         * @summary Create an Organization Transfer
         * @param {TransfersApiCreateOrganizationTransferRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOrganizationTransfer(requestParameters: TransfersApiCreateOrganizationTransferRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Transfer>> {
            const transfersCreateOrganizationTransferRequest: TransfersCreateOrganizationTransferRequest = {
                amount: requestParameters.amount,
                api_app_id: requestParameters.api_app_id,
                idempotency_key: requestParameters.idempotency_key,
                metadata: requestParameters.metadata
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOrganizationTransfer(transfersCreateOrganizationTransferRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Create a transfer.
         * @summary Create a Transfer
         * @param {TransfersApiCreateTransferRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTransfer(requestParameters: TransfersApiCreateTransferRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Transfer>> {
            const transfersCreateTransferRequest: TransfersCreateTransferRequest = {
                amount: requestParameters.amount,
                user_id: requestParameters.user_id,
                tax_exempt: requestParameters.tax_exempt,
                idempotency_key: requestParameters.idempotency_key,
                metadata: requestParameters.metadata
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTransfer(transfersCreateTransferRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * List all transfers to and from an Organization\'s wallet.
         * @summary List all Organization Transfers
         * @param {TransfersApiGetAllRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAll(requestParameters: TransfersApiGetAllRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransfersGetAllResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAll(requestParameters.limit, requestParameters.startingAfter, requestParameters.endingBefore, requestParameters.userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get a transfer by its id.
         * @summary Get a Transfer
         * @param {TransfersApiGetByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getById(requestParameters: TransfersApiGetByIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Transfer>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getById(requestParameters.transferId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get a transfer by its id.
         * @summary Get a Transfer
         * @param {TransfersApiGetById0Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getById_1(requestParameters: TransfersApiGetById0Request, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Transfer>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getById_1(requestParameters.transferId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * List all transfers.
         * @summary List all Transfers
         * @param {TransfersApiListAllRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAll(requestParameters: TransfersApiListAllRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransfersListAllResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAll(requestParameters.limit, requestParameters.startingAfter, requestParameters.endingBefore, requestParameters.userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TransfersApi - factory interface
 * @export
 */
export const TransfersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransfersApiFp(configuration)
    return {
        /**
         * Create a transfer for the organization\'s wallet to an api app.
         * @summary Create an Organization Transfer
         * @param {TransfersApiCreateOrganizationTransferRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrganizationTransfer(requestParameters: TransfersApiCreateOrganizationTransferRequest, options?: AxiosRequestConfig): AxiosPromise<Transfer> {
            return localVarFp.createOrganizationTransfer(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a transfer.
         * @summary Create a Transfer
         * @param {TransfersApiCreateTransferRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTransfer(requestParameters: TransfersApiCreateTransferRequest, options?: AxiosRequestConfig): AxiosPromise<Transfer> {
            return localVarFp.createTransfer(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * List all transfers to and from an Organization\'s wallet.
         * @summary List all Organization Transfers
         * @param {TransfersApiGetAllRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAll(requestParameters: TransfersApiGetAllRequest = {}, options?: AxiosRequestConfig): AxiosPromise<TransfersGetAllResponse> {
            return localVarFp.getAll(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a transfer by its id.
         * @summary Get a Transfer
         * @param {TransfersApiGetByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById(requestParameters: TransfersApiGetByIdRequest, options?: AxiosRequestConfig): AxiosPromise<Transfer> {
            return localVarFp.getById(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a transfer by its id.
         * @summary Get a Transfer
         * @param {TransfersApiGetById0Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById_1(requestParameters: TransfersApiGetById0Request, options?: AxiosRequestConfig): AxiosPromise<Transfer> {
            return localVarFp.getById_1(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * List all transfers.
         * @summary List all Transfers
         * @param {TransfersApiListAllRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAll(requestParameters: TransfersApiListAllRequest = {}, options?: AxiosRequestConfig): AxiosPromise<TransfersListAllResponse> {
            return localVarFp.listAll(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createOrganizationTransfer operation in TransfersApi.
 * @export
 * @interface TransfersApiCreateOrganizationTransferRequest
 */
export type TransfersApiCreateOrganizationTransferRequest = {
    
} & TransfersCreateOrganizationTransferRequest

/**
 * Request parameters for createTransfer operation in TransfersApi.
 * @export
 * @interface TransfersApiCreateTransferRequest
 */
export type TransfersApiCreateTransferRequest = {
    
} & TransfersCreateTransferRequest

/**
 * Request parameters for getAll operation in TransfersApi.
 * @export
 * @interface TransfersApiGetAllRequest
 */
export type TransfersApiGetAllRequest = {
    
    /**
    * A limit on the number of objects to be returned, between 1 and 100.
    * @type {number}
    * @memberof TransfersApiGetAll
    */
    readonly limit?: number
    
    /**
    * A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `aaa`, your subsequent call can include `starting_after`=`aaa` in order to fetch the next page of the list.
    * @type {string}
    * @memberof TransfersApiGetAll
    */
    readonly startingAfter?: string
    
    /**
    * A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `aaa`, your subsequent call can include `ending_before`=`aaa` in order to fetch the previous page of the list.
    * @type {string}
    * @memberof TransfersApiGetAll
    */
    readonly endingBefore?: string
    
    /**
    * Include only results with this user ID attached.
    * @type {string}
    * @memberof TransfersApiGetAll
    */
    readonly userId?: string
    
}

/**
 * Request parameters for getById operation in TransfersApi.
 * @export
 * @interface TransfersApiGetByIdRequest
 */
export type TransfersApiGetByIdRequest = {
    
    /**
    * Id of the transfer to fetch
    * @type {string}
    * @memberof TransfersApiGetById
    */
    readonly transferId: string
    
}

/**
 * Request parameters for getById_1 operation in TransfersApi.
 * @export
 * @interface TransfersApiGetById0Request
 */
export type TransfersApiGetById0Request = {
    
    /**
    * ID of the transfer to retrieve
    * @type {string}
    * @memberof TransfersApiGetById0
    */
    readonly transferId: string
    
}

/**
 * Request parameters for listAll operation in TransfersApi.
 * @export
 * @interface TransfersApiListAllRequest
 */
export type TransfersApiListAllRequest = {
    
    /**
    * A limit on the number of objects to be returned, between 1 and 100.
    * @type {number}
    * @memberof TransfersApiListAll
    */
    readonly limit?: number
    
    /**
    * A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `aaa`, your subsequent call can include `starting_after`=`aaa` in order to fetch the next page of the list.
    * @type {string}
    * @memberof TransfersApiListAll
    */
    readonly startingAfter?: string
    
    /**
    * A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `aaa`, your subsequent call can include `ending_before`=`aaa` in order to fetch the previous page of the list.
    * @type {string}
    * @memberof TransfersApiListAll
    */
    readonly endingBefore?: string
    
    /**
    * Include only results with this user ID attached.
    * @type {string}
    * @memberof TransfersApiListAll
    */
    readonly userId?: string
    
}

/**
 * TransfersApiGenerated - object-oriented interface
 * @export
 * @class TransfersApiGenerated
 * @extends {BaseAPI}
 */
export class TransfersApiGenerated extends BaseAPI {
    /**
     * Create a transfer for the organization\'s wallet to an api app.
     * @summary Create an Organization Transfer
     * @param {TransfersApiCreateOrganizationTransferRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransfersApiGenerated
     */
    public createOrganizationTransfer(requestParameters: TransfersApiCreateOrganizationTransferRequest, options?: AxiosRequestConfig) {
        return TransfersApiFp(this.configuration).createOrganizationTransfer(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a transfer.
     * @summary Create a Transfer
     * @param {TransfersApiCreateTransferRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransfersApiGenerated
     */
    public createTransfer(requestParameters: TransfersApiCreateTransferRequest, options?: AxiosRequestConfig) {
        return TransfersApiFp(this.configuration).createTransfer(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List all transfers to and from an Organization\'s wallet.
     * @summary List all Organization Transfers
     * @param {TransfersApiGetAllRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransfersApiGenerated
     */
    public getAll(requestParameters: TransfersApiGetAllRequest = {}, options?: AxiosRequestConfig) {
        return TransfersApiFp(this.configuration).getAll(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a transfer by its id.
     * @summary Get a Transfer
     * @param {TransfersApiGetByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransfersApiGenerated
     */
    public getById(requestParameters: TransfersApiGetByIdRequest, options?: AxiosRequestConfig) {
        return TransfersApiFp(this.configuration).getById(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a transfer by its id.
     * @summary Get a Transfer
     * @param {TransfersApiGetById0Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransfersApiGenerated
     */
    public getById_1(requestParameters: TransfersApiGetById0Request, options?: AxiosRequestConfig) {
        return TransfersApiFp(this.configuration).getById_1(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List all transfers.
     * @summary List all Transfers
     * @param {TransfersApiListAllRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransfersApiGenerated
     */
    public listAll(requestParameters: TransfersApiListAllRequest = {}, options?: AxiosRequestConfig) {
        return TransfersApiFp(this.configuration).listAll(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
