/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AppMetrics
 */
export interface AppMetrics {
    /**
     * 
     * @type {string}
     * @memberof AppMetrics
     */
    'wallet_balance': string;
    /**
     * 
     * @type {string}
     * @memberof AppMetrics
     */
    'money_out': string;
    /**
     * 
     * @type {number}
     * @memberof AppMetrics
     */
    'connected_users': number;
}

