/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppMetrics } from './app-metrics';

/**
 * 
 * @export
 * @interface App
 */
export interface App {
    /**
     * 
     * @type {string}
     * @memberof App
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof App
     */
    'name': string;
    /**
     * App verification status. Some Dots use cases require newly created apps to pass KYB review.
     * @type {string}
     * @memberof App
     */
    'status'?: AppStatusEnum;
    /**
     * 
     * @type {AppMetrics}
     * @memberof App
     */
    'metrics': AppMetrics;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof App
     */
    'metadata'?: any;
}

type AppStatusEnum = 'created' | 'in_review' | 'approved'


