/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AppsCreateNewAppRequest
 */
export interface AppsCreateNewAppRequest {
    /**
     * The name of the application.
     * @type {string}
     * @memberof AppsCreateNewAppRequest
     */
    'name': string;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof AppsCreateNewAppRequest
     */
    'metadata'?: any;
}

