/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AppsAddAchAccountResponse
 */
export interface AppsAddAchAccountResponse {
    /**
     * The last four digits of the bank account number.
     * @type {string}
     * @memberof AppsAddAchAccountResponse
     */
    'mask'?: string;
    /**
     * The name of the bank account.
     * @type {string}
     * @memberof AppsAddAchAccountResponse
     */
    'name'?: string;
}

