/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BusinessComplianceInfoDirectorsInnerAddress
 */
export interface BusinessComplianceInfoDirectorsInnerAddress {
    /**
     * 
     * @type {string}
     * @memberof BusinessComplianceInfoDirectorsInnerAddress
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof BusinessComplianceInfoDirectorsInnerAddress
     */
    'country': string;
    /**
     * 
     * @type {string}
     * @memberof BusinessComplianceInfoDirectorsInnerAddress
     */
    'line1': string;
    /**
     * 
     * @type {string}
     * @memberof BusinessComplianceInfoDirectorsInnerAddress
     */
    'line2'?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessComplianceInfoDirectorsInnerAddress
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessComplianceInfoDirectorsInnerAddress
     */
    'zip': string;
}

