/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessComplianceInfoCompanyInfo } from './business-compliance-info-company-info';
import { BusinessComplianceInfoContactInfo } from './business-compliance-info-contact-info';
import { BusinessComplianceInfoDirectorsInner } from './business-compliance-info-directors-inner';
import { BusinessComplianceInfoFlowOfFunds } from './business-compliance-info-flow-of-funds';

/**
 * 
 * @export
 * @interface BusinessComplianceInfo
 */
export interface BusinessComplianceInfo {
    /**
     * 
     * @type {BusinessComplianceInfoCompanyInfo}
     * @memberof BusinessComplianceInfo
     */
    'company_info': BusinessComplianceInfoCompanyInfo;
    /**
     * 
     * @type {BusinessComplianceInfoContactInfo}
     * @memberof BusinessComplianceInfo
     */
    'contact_info': BusinessComplianceInfoContactInfo;
    /**
     * 
     * @type {Array<BusinessComplianceInfoDirectorsInner>}
     * @memberof BusinessComplianceInfo
     */
    'directors': Array<BusinessComplianceInfoDirectorsInner>;
    /**
     * 
     * @type {BusinessComplianceInfoFlowOfFunds}
     * @memberof BusinessComplianceInfo
     */
    'flow_of_funds': BusinessComplianceInfoFlowOfFunds;
}

