/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessComplianceInfoDirectorsInnerAddress } from './business-compliance-info-directors-inner-address';

/**
 * 
 * @export
 * @interface BusinessComplianceInfoDirectorsInner
 */
export interface BusinessComplianceInfoDirectorsInner {
    /**
     * Employee title or ownership role
     * @type {string}
     * @memberof BusinessComplianceInfoDirectorsInner
     */
    'title': string;
    /**
     * 
     * @type {BusinessComplianceInfoDirectorsInnerAddress}
     * @memberof BusinessComplianceInfoDirectorsInner
     */
    'address': BusinessComplianceInfoDirectorsInnerAddress;
    /**
     * Date of birth
     * @type {string}
     * @memberof BusinessComplianceInfoDirectorsInner
     */
    'dob': string;
    /**
     * Contact email, needs to be verifiable
     * @type {string}
     * @memberof BusinessComplianceInfoDirectorsInner
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof BusinessComplianceInfoDirectorsInner
     */
    'first_name': string;
    /**
     * 
     * @type {string}
     * @memberof BusinessComplianceInfoDirectorsInner
     */
    'last_name': string;
    /**
     * Percentage of company owned by this person
     * @type {number}
     * @memberof BusinessComplianceInfoDirectorsInner
     */
    'ownership_percentage': number;
    /**
     * 
     * @type {string}
     * @memberof BusinessComplianceInfoDirectorsInner
     */
    'phone': string;
}

