/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BusinessComplianceInfoFlowOfFunds
 */
export interface BusinessComplianceInfoFlowOfFunds {
    /**
     * Flow of funds
     * @type {string}
     * @memberof BusinessComplianceInfoFlowOfFunds
     */
    'reasons': string;
    /**
     * Description of the business
     * @type {string}
     * @memberof BusinessComplianceInfoFlowOfFunds
     */
    'usage': string;
}

