/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CheckoutSessionLineItemsInner } from './checkout-session-line-items-inner';

/**
 * 
 * @export
 * @interface CheckoutSession
 */
export interface CheckoutSession {
    /**
     * 
     * @type {string}
     * @memberof CheckoutSession
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSession
     */
    'status'?: CheckoutSessionStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSession
     */
    'payment_intent_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSession
     */
    'success_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSession
     */
    'cancel_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSession
     */
    'checkout_session_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSession
     */
    'client_reference_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSession
     */
    'expiry'?: string;
    /**
     * 
     * @type {object}
     * @memberof CheckoutSession
     */
    'metadata'?: object;
    /**
     * 
     * @type {Array<CheckoutSessionLineItemsInner>}
     * @memberof CheckoutSession
     */
    'line_items'?: Array<CheckoutSessionLineItemsInner>;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSession
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSession
     */
    'updated'?: string;
    /**
     * `payment-customer` ID
     * @type {string}
     * @memberof CheckoutSession
     */
    'customer_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSession
     */
    'customer_email'?: string;
    /**
     * 
     * @type {number}
     * @memberof CheckoutSession
     */
    'amount_total'?: number;
}

type CheckoutSessionStatusEnum = 'open' | 'complete' | 'expired'


