/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CheckoutsessionsCreateSessionRequestLineItemsInnerPriceData } from './checkoutsessions-create-session-request-line-items-inner-price-data';

/**
 * 
 * @export
 * @interface CheckoutsessionsCreateSessionRequestLineItemsInner
 */
export interface CheckoutsessionsCreateSessionRequestLineItemsInner {
    /**
     * 
     * @type {CheckoutsessionsCreateSessionRequestLineItemsInnerPriceData}
     * @memberof CheckoutsessionsCreateSessionRequestLineItemsInner
     */
    'price_data': CheckoutsessionsCreateSessionRequestLineItemsInnerPriceData;
    /**
     * 
     * @type {number}
     * @memberof CheckoutsessionsCreateSessionRequestLineItemsInner
     */
    'quantity': number;
}

