/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CheckoutsessionsCreateSessionRequestLineItemsInnerPriceDataProductData
 */
export interface CheckoutsessionsCreateSessionRequestLineItemsInnerPriceDataProductData {
    /**
     * 
     * @type {string}
     * @memberof CheckoutsessionsCreateSessionRequestLineItemsInnerPriceDataProductData
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutsessionsCreateSessionRequestLineItemsInnerPriceDataProductData
     */
    'name': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CheckoutsessionsCreateSessionRequestLineItemsInnerPriceDataProductData
     */
    'images'?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof CheckoutsessionsCreateSessionRequestLineItemsInnerPriceDataProductData
     */
    'metadata'?: object;
}

