/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CheckoutsessionsCreateSessionRequestLineItemsInner } from './checkoutsessions-create-session-request-line-items-inner';

/**
 * 
 * @export
 * @interface CheckoutsessionsCreateSessionRequest
 */
export interface CheckoutsessionsCreateSessionRequest {
    /**
     * 
     * @type {Set<CheckoutsessionsCreateSessionRequestLineItemsInner>}
     * @memberof CheckoutsessionsCreateSessionRequest
     */
    'line_items': Set<CheckoutsessionsCreateSessionRequestLineItemsInner>;
    /**
     * 
     * @type {string}
     * @memberof CheckoutsessionsCreateSessionRequest
     */
    'customer_email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutsessionsCreateSessionRequest
     */
    'client_reference_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutsessionsCreateSessionRequest
     */
    'success_url': string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutsessionsCreateSessionRequest
     */
    'cancel_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutsessionsCreateSessionRequest
     */
    'mode': CheckoutsessionsCreateSessionRequestModeEnum;
    /**
     * Supply a Dots user ID in place of a customer ID
     * @type {string}
     * @memberof CheckoutsessionsCreateSessionRequest
     */
    'user_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutsessionsCreateSessionRequest
     */
    'customer_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof CheckoutsessionsCreateSessionRequest
     */
    'expires_in'?: number;
    /**
     * 
     * @type {object}
     * @memberof CheckoutsessionsCreateSessionRequest
     */
    'metadata'?: object;
}

type CheckoutsessionsCreateSessionRequestModeEnum = 'payment'


