/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DisputeFile } from './dispute-file';

/**
 * 
 * @export
 * @interface Dispute
 */
export interface Dispute {
    /**
     * 
     * @type {string}
     * @memberof Dispute
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Dispute
     */
    'payment_intent_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Dispute
     */
    'status'?: DisputeStatusEnum;
    /**
     * 
     * @type {Array<DisputeFile>}
     * @memberof Dispute
     */
    'evidence'?: Array<DisputeFile>;
}

type DisputeStatusEnum = 'needs_response' | 'under_review' | 'closed' | 'warning_needs_response' | 'warning_under_review' | 'warning_closed' | 'won' | 'lost'


