/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Dispute } from './dispute';

/**
 * 
 * @export
 * @interface DisputesGetAllResponse
 */
export interface DisputesGetAllResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DisputesGetAllResponse
     */
    'has_more'?: boolean;
    /**
     * 
     * @type {Array<Dispute>}
     * @memberof DisputesGetAllResponse
     */
    'data'?: Array<Dispute>;
}

