/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Flow } from './flow';

/**
 * 
 * @export
 * @interface FlowsListAllResponse
 */
export interface FlowsListAllResponse {
    /**
     * `true` if there are more `flows`.
     * @type {boolean}
     * @memberof FlowsListAllResponse
     */
    'has_more'?: boolean;
    /**
     * Array of `flow` objects.
     * @type {Array<Flow>}
     * @memberof FlowsListAllResponse
     */
    'data'?: Array<Flow>;
}

