/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FlowsCreateNewFlowRequestStepsInner } from './flows-create-new-flow-request-steps-inner';

/**
 * 
 * @export
 * @interface FlowsCreateNewFlowRequest
 */
export interface FlowsCreateNewFlowRequest {
    /**
     * A list of steps. Can either be a string or an object with additional properties. Example: A `redirect` step looks like {\"name\": \"redirect\", \"redirect_url\": \"https://example.com\"}
     * @type {Set<FlowsCreateNewFlowRequestStepsInner>}
     * @memberof FlowsCreateNewFlowRequest
     */
    'steps': Set<FlowsCreateNewFlowRequestStepsInner>;
    /**
     * The user\'s id.
     * @type {string}
     * @memberof FlowsCreateNewFlowRequest
     */
    'user_id'?: string;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof FlowsCreateNewFlowRequest
     */
    'metadata'?: any;
}

