/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentCustomer } from './payment-customer';

/**
 * 
 * @export
 * @interface PaymentcustomersListAllResponse
 */
export interface PaymentcustomersListAllResponse {
    /**
     * 
     * @type {Array<PaymentCustomer>}
     * @memberof PaymentcustomersListAllResponse
     */
    'data'?: Array<PaymentCustomer>;
    /**
     * `true` if there are more objects.
     * @type {boolean}
     * @memberof PaymentcustomersListAllResponse
     */
    'has_more'?: boolean;
}

