/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentintentsGetByIdResponse
 */
export interface PaymentintentsGetByIdResponse {
    /**
     * 
     * @type {string}
     * @memberof PaymentintentsGetByIdResponse
     */
    'error'?: PaymentintentsGetByIdResponseErrorEnum;
}

type PaymentintentsGetByIdResponseErrorEnum = 'PaymentIntent not found'


