/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentCustomer
 */
export interface PaymentCustomer {
    /**
     * 
     * @type {string}
     * @memberof PaymentCustomer
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCustomer
     */
    'user_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCustomer
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCustomer
     */
    'country_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCustomer
     */
    'phone_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCustomer
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCustomer
     */
    'middle_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCustomer
     */
    'last_name'?: string;
    /**
     * 
     * @type {object}
     * @memberof PaymentCustomer
     */
    'metadata'?: object;
    /**
     * 
     * @type {string}
     * @memberof PaymentCustomer
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCustomer
     */
    'updated'?: string;
}

