/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentcustomersCreateCustomerResponse
 */
export interface PaymentcustomersCreateCustomerResponse {
    /**
     * 
     * @type {string}
     * @memberof PaymentcustomersCreateCustomerResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentcustomersCreateCustomerResponse
     */
    'user_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentcustomersCreateCustomerResponse
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentcustomersCreateCustomerResponse
     */
    'country_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentcustomersCreateCustomerResponse
     */
    'phone_number'?: string;
}

