/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentintentsCreateIntentRequestTransferData
 */
export interface PaymentintentsCreateIntentRequestTransferData {
    /**
     * The destination user to send the funds to. This is `amount` - transactions fees - `application_fee`.
     * @type {string}
     * @memberof PaymentintentsCreateIntentRequestTransferData
     */
    'destination_user_id'?: string;
}

