/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentmethodsDetachPaymentMethodRequest
 */
export interface PaymentmethodsDetachPaymentMethodRequest {
    /**
     * ID of the payment customer to detach the payment method from.
     * @type {string}
     * @memberof PaymentmethodsDetachPaymentMethodRequest
     */
    'customer_id'?: string;
}

