/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentMethod } from './payment-method';

/**
 * 
 * @export
 * @interface PaymentmethodsListAllPaymentCustomerResponse
 */
export interface PaymentmethodsListAllPaymentCustomerResponse {
    /**
     * List of payment methods.
     * @type {Array<PaymentMethod>}
     * @memberof PaymentmethodsListAllPaymentCustomerResponse
     */
    'data'?: Array<PaymentMethod>;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentmethodsListAllPaymentCustomerResponse
     */
    'has_more'?: boolean;
}

