/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentMethod
 */
export interface PaymentMethod {
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    'description'?: string;
    /**
     * ID of the `payment-method`.
     * @type {string}
     * @memberof PaymentMethod
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    'platform': PaymentMethodPlatformEnum;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    'mask'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    'phone_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    'cash_tag'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    'currency'?: string;
}

type PaymentMethodPlatformEnum = 'ach' | 'paypal' | 'venmo' | 'cash_app' | 'intl_transfer'


