/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentintentsConfirmIntentRequest
 */
export interface PaymentintentsConfirmIntentRequest {
    /**
     * ID of the payment method to confirm the intent with.
     * @type {string}
     * @memberof PaymentintentsConfirmIntentRequest
     */
    'payment_method_id': string;
}

