/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentmethodsAttachPaymentMethodRequest
 */
export interface PaymentmethodsAttachPaymentMethodRequest {
    /**
     * ID of the payment customer
     * @type {string}
     * @memberof PaymentmethodsAttachPaymentMethodRequest
     */
    'customer_id': string;
}

