/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayoutsSendPayoutRequestPayee } from './payouts-send-payout-request-payee';

/**
 * 
 * @export
 * @interface PayoutrequestsSubmitRequestRequest
 */
export interface PayoutrequestsSubmitRequestRequest {
    /**
     * The amount in cents to pay the user.
     * @type {number}
     * @memberof PayoutrequestsSubmitRequestRequest
     */
    'amount': number;
    /**
     * The user\'s id. `user_id` or `payee` is required.
     * @type {string}
     * @memberof PayoutrequestsSubmitRequestRequest
     */
    'user_id'?: string;
    /**
     * 
     * @type {PayoutsSendPayoutRequestPayee}
     * @memberof PayoutrequestsSubmitRequestRequest
     */
    'payee'?: PayoutsSendPayoutRequestPayee;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof PayoutrequestsSubmitRequestRequest
     */
    'metadata'?: any;
    /**
     * Add a memo to payout request
     * @type {string}
     * @memberof PayoutrequestsSubmitRequestRequest
     */
    'memo'?: string;
}

