/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayoutlinksCreatePayoutLinkRequestDelivery } from './payoutlinks-create-payout-link-request-delivery';
import { PayoutlinksCreatePayoutLinkRequestPayee } from './payoutlinks-create-payout-link-request-payee';

/**
 * 
 * @export
 * @interface PayoutlinksCreatePayoutLinkRequest
 */
export interface PayoutlinksCreatePayoutLinkRequest {
    /**
     * The user\'s id.
     * @type {string}
     * @memberof PayoutlinksCreatePayoutLinkRequest
     */
    'user_id'?: string;
    /**
     * 
     * @type {PayoutlinksCreatePayoutLinkRequestPayee}
     * @memberof PayoutlinksCreatePayoutLinkRequest
     */
    'payee'?: PayoutlinksCreatePayoutLinkRequestPayee;
    /**
     * Amount to be paid in cents.
     * @type {number}
     * @memberof PayoutlinksCreatePayoutLinkRequest
     */
    'amount': number;
    /**
     * 
     * @type {PayoutlinksCreatePayoutLinkRequestDelivery}
     * @memberof PayoutlinksCreatePayoutLinkRequest
     */
    'delivery'?: PayoutlinksCreatePayoutLinkRequestDelivery;
    /**
     * Force the collection of 1099 or W-8 information. Defaults to `false`.
     * @type {boolean}
     * @memberof PayoutlinksCreatePayoutLinkRequest
     */
    'force_collect_compliance_information'?: boolean;
    /**
     * Payout links marked as `tax_exempt` will not be counted towards the 1099 threshold.
     * @type {boolean}
     * @memberof PayoutlinksCreatePayoutLinkRequest
     */
    'tax_exempt'?: boolean;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof PayoutlinksCreatePayoutLinkRequest
     */
    'metadata'?: any;
    /**
     * Add a memo to the top of the Payout Link
     * @type {string}
     * @memberof PayoutlinksCreatePayoutLinkRequest
     */
    'memo'?: string;
    /**
     * Unique UUID key that prevents duplicate requests from being processed. If a payout link with the idempotency key exists, a new link will not be created and the existing link will be returned instead.
     * @type {any}
     * @memberof PayoutlinksCreatePayoutLinkRequest
     */
    'idempotency_key'?: any;
    /**
     * Overrides the setting for which party will pay fees on this payout. This takes precedence over the default for your application.
     * @type {string}
     * @memberof PayoutlinksCreatePayoutLinkRequest
     */
    'payout_fee_party'?: PayoutlinksCreatePayoutLinkRequestPayoutFeePartyEnum;
    /**
     * Array of steps in the flow.
     * @type {Array<string>}
     * @memberof PayoutlinksCreatePayoutLinkRequest
     */
    'additional_steps'?: Array<PayoutlinksCreatePayoutLinkRequestAdditionalStepsEnum>;
}

type PayoutlinksCreatePayoutLinkRequestPayoutFeePartyEnum = 'user' | 'platform'
type PayoutlinksCreatePayoutLinkRequestAdditionalStepsEnum = 'compliance' | 'id-verification' | 'background-check' | 'manage-payments' | 'manage-payouts' | 'payout' | 'redirect'


