/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PayoutsCreatePayoutRequest
 */
export interface PayoutsCreatePayoutRequest {
    /**
     * ID of the `user` who you are creating the payout for.
     * @type {string}
     * @memberof PayoutsCreatePayoutRequest
     */
    'user_id': string;
    /**
     * Amount in cents to payout the user.
     * @type {number}
     * @memberof PayoutsCreatePayoutRequest
     */
    'amount': number;
    /**
     * Platform that you are paying out the `user` through,
     * @type {string}
     * @memberof PayoutsCreatePayoutRequest
     */
    'platform': PayoutsCreatePayoutRequestPlatformEnum;
    /**
     * The bank account ID you are paying to. Required for `ach` and `intl_bank`.
     * @type {string}
     * @memberof PayoutsCreatePayoutRequest
     */
    'account_id'?: string;
    /**
     * Creates a transfer for the amount to the user before creating the payout. The funds are returned if the payout does not succeed.
     * @type {boolean}
     * @memberof PayoutsCreatePayoutRequest
     */
    'fund'?: boolean;
    /**
     * UUID that will be used to idempotently handle requests. Transfers with existing idempotency keys will be rejected.
     * @type {string}
     * @memberof PayoutsCreatePayoutRequest
     */
    'idempotency_key'?: string;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof PayoutsCreatePayoutRequest
     */
    'metadata'?: any;
}

type PayoutsCreatePayoutRequestPlatformEnum = 'paypal' | 'venmo' | 'ach' | 'bank_transfer' | 'cash_app' | 'payoneer' | 'airtm' | 'default'


