/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayoutLinkDelivery } from './payout-link-delivery';
import { PayoutLinkPayee } from './payout-link-payee';

/**
 * 
 * @export
 * @interface PayoutLink
 */
export interface PayoutLink {
    /**
     * ID of the `payout-link`.
     * @type {string}
     * @memberof PayoutLink
     */
    'id'?: string;
    /**
     * Date the `payout-link` was created.
     * @type {string}
     * @memberof PayoutLink
     */
    'created'?: string;
    /**
     * URL to access the `payout-link`.
     * @type {string}
     * @memberof PayoutLink
     */
    'link'?: string;
    /**
     * The amount to pay in cents.
     * @type {number}
     * @memberof PayoutLink
     */
    'amount'?: number;
    /**
     * Status of the `payout-link`.
     * @type {string}
     * @memberof PayoutLink
     */
    'status'?: PayoutLinkStatusEnum;
    /**
     * 
     * @type {PayoutLinkPayee}
     * @memberof PayoutLink
     */
    'payee'?: PayoutLinkPayee;
    /**
     * 
     * @type {PayoutLinkDelivery}
     * @memberof PayoutLink
     */
    'delivery'?: PayoutLinkDelivery;
    /**
     * Transfers marked as `tax_exempt` will not be counted towards the 1099 threshold.
     * @type {boolean}
     * @memberof PayoutLink
     */
    'tax_exempt'?: boolean;
    /**
     * ID of the `user` that has claimed the `payout-link`.
     * @type {string}
     * @memberof PayoutLink
     */
    'claimed_user_id'?: string;
    /**
     * ID of the payout flow UI that is sent to the user.
     * @type {string}
     * @memberof PayoutLink
     */
    'flow_id'?: string;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof PayoutLink
     */
    'metadata'?: any;
}

type PayoutLinkStatusEnum = 'sent' | 'claimed' | 'delivery_pending' | 'delivery_failed' | 'delivered' | 'canceled'


