/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the payee. It is used to pre-fill information.
 * @export
 * @interface PayoutLinkPayee
 */
export interface PayoutLinkPayee {
    /**
     * Payee\'s first name.
     * @type {string}
     * @memberof PayoutLinkPayee
     */
    'first_name'?: string;
    /**
     * Payee\'s last name.
     * @type {string}
     * @memberof PayoutLinkPayee
     */
    'last_name'?: string;
    /**
     * Payee\'s email address.
     * @type {string}
     * @memberof PayoutLinkPayee
     */
    'email'?: string;
    /**
     * Country code of the payee\'s phone number e.g. \"1\" for USA.
     * @type {string}
     * @memberof PayoutLinkPayee
     */
    'country_code'?: string;
    /**
     * Rest of the payee\'s phone number.
     * @type {string}
     * @memberof PayoutLinkPayee
     */
    'phone_number'?: string;
}

