/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayoutLink } from './payout-link';

/**
 * 
 * @export
 * @interface PayoutlinksListAllResponse
 */
export interface PayoutlinksListAllResponse {
    /**
     * `true` if there are more `payout-links`.
     * @type {boolean}
     * @memberof PayoutlinksListAllResponse
     */
    'has_more'?: boolean;
    /**
     * Array of `payout-links`.
     * @type {Array<PayoutLink>}
     * @memberof PayoutlinksListAllResponse
     */
    'data'?: Array<PayoutLink>;
}

