/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PayoutRequestPayee
 */
export interface PayoutRequestPayee {
    /**
     * 
     * @type {string}
     * @memberof PayoutRequestPayee
     */
    'country_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayoutRequestPayee
     */
    'phone_number'?: string;
}

