/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayoutsSendPayoutRequestDelivery } from './payouts-send-payout-request-delivery';
import { PayoutsSendPayoutRequestPayee } from './payouts-send-payout-request-payee';

/**
 * 
 * @export
 * @interface PayoutsSendPayoutRequest
 */
export interface PayoutsSendPayoutRequest {
    /**
     * The amount in cents to pay the user.
     * @type {number}
     * @memberof PayoutsSendPayoutRequest
     */
    'amount': number;
    /**
     * The user\'s id. `user_id` or `payee` is required.
     * @type {string}
     * @memberof PayoutsSendPayoutRequest
     */
    'user_id'?: string;
    /**
     * 
     * @type {PayoutsSendPayoutRequestPayee}
     * @memberof PayoutsSendPayoutRequest
     */
    'payee'?: PayoutsSendPayoutRequestPayee;
    /**
     * 
     * @type {PayoutsSendPayoutRequestDelivery}
     * @memberof PayoutsSendPayoutRequest
     */
    'delivery'?: PayoutsSendPayoutRequestDelivery;
    /**
     * Collect 1099 or w8-ben information.
     * @type {boolean}
     * @memberof PayoutsSendPayoutRequest
     */
    'force_collect_compliance_information'?: boolean;
    /**
     * Array of steps in the flow.
     * @type {Array<string>}
     * @memberof PayoutsSendPayoutRequest
     */
    'additional_steps'?: Array<PayoutsSendPayoutRequestAdditionalStepsEnum>;
    /**
     * Payouts marked as `tax_exempt` will not be counted towards the 1099 threshold.
     * @type {boolean}
     * @memberof PayoutsSendPayoutRequest
     */
    'tax_exempt'?: boolean;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof PayoutsSendPayoutRequest
     */
    'metadata'?: any;
    /**
     * Add a memo to the top of the Payout Link
     * @type {string}
     * @memberof PayoutsSendPayoutRequest
     */
    'memo'?: string;
    /**
     * Unique UUID key that prevents duplicate requests from being processed. If a payout link with the idempotency key exists, a new link will not be created and the existing link will be returned instead.
     * @type {any}
     * @memberof PayoutsSendPayoutRequest
     */
    'idempotency_key'?: any;
    /**
     * Overrides the setting for which party will pay fees on this payout. This takes precedence over the default for your application.
     * @type {string}
     * @memberof PayoutsSendPayoutRequest
     */
    'payout_fee_party'?: PayoutsSendPayoutRequestPayoutFeePartyEnum;
}

type PayoutsSendPayoutRequestAdditionalStepsEnum = 'compliance' | 'id-verification' | 'background-check' | 'manage-payments' | 'manage-payouts' | 'payout' | 'redirect'
type PayoutsSendPayoutRequestPayoutFeePartyEnum = 'user' | 'platform'


