/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayoutLink } from './payout-link';
import { PayoutRequestPayee } from './payout-request-payee';
import { User } from './user';

/**
 * 
 * @export
 * @interface PayoutRequest
 */
export interface PayoutRequest {
    /**
     * ID of the `payout-request`.
     * @type {string}
     * @memberof PayoutRequest
     */
    'id'?: string;
    /**
     * Date that the `payout-request` was created.
     * @type {string}
     * @memberof PayoutRequest
     */
    'created'?: string;
    /**
     * Amount in cents of the `payout-request`.
     * @type {number}
     * @memberof PayoutRequest
     */
    'amount'?: number;
    /**
     * Status of the `payout-request`.
     * @type {string}
     * @memberof PayoutRequest
     */
    'status'?: PayoutRequestStatusEnum;
    /**
     * 
     * @type {PayoutRequestPayee}
     * @memberof PayoutRequest
     */
    'payee'?: PayoutRequestPayee;
    /**
     * 
     * @type {PayoutLink}
     * @memberof PayoutRequest
     */
    'payout-link'?: PayoutLink;
    /**
     * 
     * @type {User}
     * @memberof PayoutRequest
     */
    'user'?: User;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof PayoutRequest
     */
    'metadata'?: any;
    /**
     * 
     * @type {any}
     * @memberof PayoutRequest
     */
    'memo'?: any;
}

type PayoutRequestStatusEnum = 'created' | 'approved' | 'rejected'


