/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RefundsCreateRefundRequest
 */
export interface RefundsCreateRefundRequest {
    /**
     * Amount in cents
     * @type {number}
     * @memberof RefundsCreateRefundRequest
     */
    'amount': number;
    /**
     * ID of the `payment_intent` you are refunding.
     * @type {string}
     * @memberof RefundsCreateRefundRequest
     */
    'payment_intent_id': string;
    /**
     * 
     * @type {string}
     * @memberof RefundsCreateRefundRequest
     */
    'reason'?: RefundsCreateRefundRequestReasonEnum;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {boolean}
     * @memberof RefundsCreateRefundRequest
     */
    'metadata'?: boolean;
}

type RefundsCreateRefundRequestReasonEnum = 'duplicate' | 'fraudulent' | 'requested_by_customer' | 'expired_uncaptured_charge' | 'partial_capture'


