/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface StepWithOptions
 */
export interface StepWithOptions {
    /**
     * The `step` name.
     * @type {string}
     * @memberof StepWithOptions
     */
    'name': StepWithOptionsNameEnum;
    /**
     * Enable or disable setting auto payout on the `payout` or `manage-payout` step. Defaults to `true`.
     * @type {boolean}
     * @memberof StepWithOptions
     */
    'auto_payout_enabled'?: boolean;
    /**
     * URL to redirect for the `redirect` step.
     * @type {string}
     * @memberof StepWithOptions
     */
    'redirect_url'?: string;
    /**
     * Hide the continue button on the flow UI. Defaults to `false`.
     * @type {boolean}
     * @memberof StepWithOptions
     */
    'hide_continue_button'?: boolean;
}

type StepWithOptionsNameEnum = 'compliance' | 'id-verification' | 'manage-payouts' | 'manage-payments' | 'payout' | 'background-check' | 'redirect'


