/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TransfersCreateTransferRequest
 */
export interface TransfersCreateTransferRequest {
    /**
     * The amount in cents to transfer. Negative amount transfers money from the `app` to the `user`.
     * @type {number}
     * @memberof TransfersCreateTransferRequest
     */
    'amount': number;
    /**
     * The user\'s id.
     * @type {string}
     * @memberof TransfersCreateTransferRequest
     */
    'user_id': string;
    /**
     * Transfers marked as `tax_exempt` will not be counted towards the 1099 threshold.
     * @type {any}
     * @memberof TransfersCreateTransferRequest
     */
    'tax_exempt'?: any;
    /**
     * UUID that will be used to idempotently handle requests. Transfers with existing idempotency keys will be rejected.
     * @type {any}
     * @memberof TransfersCreateTransferRequest
     */
    'idempotency_key'?: any;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof TransfersCreateTransferRequest
     */
    'metadata'?: any;
}

