/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'source_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'destination_name'?: string;
    /**
     * The general category of the transaction
     * @type {string}
     * @memberof Transaction
     */
    'type'?: TransactionTypeEnum;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof Transaction
     */
    'metadata'?: any;
}

type TransactionTypeEnum = 'balance' | 'refill' | 'payout' | 'payment' | 'fee' | 'surrogate'


