/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TransfersCreateOrganizationTransferRequest
 */
export interface TransfersCreateOrganizationTransferRequest {
    /**
     * The amount in cents to transfer. Negative amount transfers money from the `app` to the `user`.
     * @type {number}
     * @memberof TransfersCreateOrganizationTransferRequest
     */
    'amount': number;
    /**
     * API App ID to transact with.
     * @type {string}
     * @memberof TransfersCreateOrganizationTransferRequest
     */
    'api_app_id': string;
    /**
     * 
     * @type {string}
     * @memberof TransfersCreateOrganizationTransferRequest
     */
    'idempotency_key'?: string;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof TransfersCreateOrganizationTransferRequest
     */
    'metadata'?: any;
}

