/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransferBatchItem } from './transfer-batch-item';

/**
 * 
 * @export
 * @interface TransferbatchesCreateBatchResponse
 */
export interface TransferbatchesCreateBatchResponse {
    /**
     * 
     * @type {string}
     * @memberof TransferbatchesCreateBatchResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferbatchesCreateBatchResponse
     */
    'status'?: TransferbatchesCreateBatchResponseStatusEnum;
    /**
     * 
     * @type {object}
     * @memberof TransferbatchesCreateBatchResponse
     */
    'metadata'?: object;
    /**
     * 
     * @type {Array<TransferBatchItem>}
     * @memberof TransferbatchesCreateBatchResponse
     */
    'items'?: Array<TransferBatchItem>;
}

type TransferbatchesCreateBatchResponseStatusEnum = 'pending' | 'completed'


