/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransferbatchesListAllResponseDataInner } from './transferbatches-list-all-response-data-inner';

/**
 * 
 * @export
 * @interface TransferbatchesListAllResponse
 */
export interface TransferbatchesListAllResponse {
    /**
     * 
     * @type {Array<TransferbatchesListAllResponseDataInner>}
     * @memberof TransferbatchesListAllResponse
     */
    'data'?: Array<TransferbatchesListAllResponseDataInner>;
    /**
     * `true` if there are more objects.
     * @type {boolean}
     * @memberof TransferbatchesListAllResponse
     */
    'has_more'?: boolean;
}

