/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransferBatchItem } from './transfer-batch-item';

/**
 * 
 * @export
 * @interface TransferbatchesListAllResponseDataInner
 */
export interface TransferbatchesListAllResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof TransferbatchesListAllResponseDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransferbatchesListAllResponseDataInner
     */
    'status'?: TransferbatchesListAllResponseDataInnerStatusEnum;
    /**
     * 
     * @type {object}
     * @memberof TransferbatchesListAllResponseDataInner
     */
    'metadata'?: object;
    /**
     * 
     * @type {Array<TransferBatchItem>}
     * @memberof TransferbatchesListAllResponseDataInner
     */
    'items'?: Array<TransferBatchItem>;
}

type TransferbatchesListAllResponseDataInnerStatusEnum = 'completed' | 'pending'


