/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Transaction } from './transaction';
import { TransferExternalData } from './transfer-external-data';

/**
 * 
 * @export
 * @interface Transfer
 */
export interface Transfer {
    /**
     * 
     * @type {string}
     * @memberof Transfer
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Transfer
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof Transfer
     */
    'user_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Transfer
     */
    'status'?: TransferStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Transfer
     */
    'type'?: TransferTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof Transfer
     */
    'amount'?: number;
    /**
     * 
     * @type {TransferExternalData}
     * @memberof Transfer
     */
    'external_data'?: TransferExternalData;
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof Transfer
     */
    'transactions'?: Array<Transaction>;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof Transfer
     */
    'metadata'?: any;
}

type TransferStatusEnum = 'created' | 'pending' | 'failed' | 'completed' | 'flagged'
type TransferTypeEnum = 'refill' | 'payout' | 'balance'


