/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Address of the user or their business.
 * @export
 * @interface UsersSubmitComplianceInfoRequestW8benAddress
 */
export interface UsersSubmitComplianceInfoRequestW8benAddress {
    /**
     * Address line 1.
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8benAddress
     */
    'line_1': string;
    /**
     * Address line 2.
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8benAddress
     */
    'line_2'?: string;
    /**
     * City.
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8benAddress
     */
    'city': string;
    /**
     * State.
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8benAddress
     */
    'state': string;
    /**
     * Country.
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8benAddress
     */
    'country': string;
    /**
     * Postal code or Zip Code.
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8benAddress
     */
    'postcode': string;
}

