/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsersUpdateUserObjectRequest
 */
export interface UsersUpdateUserObjectRequest {
    /**
     * Configures the user\'s default payout method. Must be a payout method already configured by the user.
     * @type {string}
     * @memberof UsersUpdateUserObjectRequest
     */
    'default_payout_method'?: UsersUpdateUserObjectRequestDefaultPayoutMethodEnum;
    /**
     * Enables auto payout for the user whenever a default payout method is defined
     * @type {boolean}
     * @memberof UsersUpdateUserObjectRequest
     */
    'auto_payout_enabled'?: boolean;
    /**
     * Arbitrary metadata
     * @type {any}
     * @memberof UsersUpdateUserObjectRequest
     */
    'metadata'?: any;
}

type UsersUpdateUserObjectRequestDefaultPayoutMethodEnum = 'paypal' | 'venmo' | 'cash_app' | 'ach' | 'intl_bank'


