/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UsersSubmitComplianceInfoRequestW8benAddress } from './users-submit-compliance-info-request-w8ben-address';
import { UsersSubmitComplianceInfoRequestW8benSignature } from './users-submit-compliance-info-request-w8ben-signature';

/**
 * W8-BEN form for foreign payees.
 * @export
 * @interface UsersSubmitComplianceInfoRequestW8ben
 */
export interface UsersSubmitComplianceInfoRequestW8ben {
    /**
     * Full name of the person.
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8ben
     */
    'name': string;
    /**
     * The two-letter ISO country code associated with the beneficial owner\'s citizenship.
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8ben
     */
    'citizenship_country': string;
    /**
     * Date of birth of the user.
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8ben
     */
    'date_of_birth': string;
    /**
     * SSN
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8ben
     */
    'tin': string;
    /**
     * The tax identification number associated with the beneficial owner\'s country of residence.
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8ben
     */
    'foreign_tax_id'?: string;
    /**
     * The two-letter ISO country code of the country for tax treaty purposes.
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8ben
     */
    'tax_treaty_country'?: string;
    /**
     * The article and paragraph of the citation claimed for tax treaty purposes.
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8ben
     */
    'tax_treaty_citation'?: string;
    /**
     * The withholding rate claimed for tax treaty purposes. For example, a 15% rate would be represented as 0.15.
     * @type {number}
     * @memberof UsersSubmitComplianceInfoRequestW8ben
     */
    'tax_treaty_rate'?: number;
    /**
     * The type of income for tax treaty purposes. Valid values are - interest1 (Interest Paid by U.S. Obligors) - dividend6 (Dividends Paid by U.S. Corporations) - dividend7 (Dividends Qualifying for Direct Dividend Rate) - pension15 (Pensions and Annuities) - socialSecurity (Social Security) - equipment10 (Industrial Equipment) - knowhow10 (Know-How/Other Industrial Royalties) - patent10 (Patents) - film11 (Film & TV) - copyright12 (Copyrights)
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8ben
     */
    'tax_treaty_income_type'?: UsersSubmitComplianceInfoRequestW8benTaxTreatyIncomeTypeEnum;
    /**
     * An optional explanation for the tax treaty claimed.
     * @type {string}
     * @memberof UsersSubmitComplianceInfoRequestW8ben
     */
    'tax_treaty_explanation'?: string;
    /**
     * 
     * @type {UsersSubmitComplianceInfoRequestW8benAddress}
     * @memberof UsersSubmitComplianceInfoRequestW8ben
     */
    'address': UsersSubmitComplianceInfoRequestW8benAddress;
    /**
     * 
     * @type {UsersSubmitComplianceInfoRequestW8benSignature}
     * @memberof UsersSubmitComplianceInfoRequestW8ben
     */
    'signature': UsersSubmitComplianceInfoRequestW8benSignature;
}

type UsersSubmitComplianceInfoRequestW8benTaxTreatyIncomeTypeEnum = 'interest1' | 'dividend6' | 'dividend7' | 'pension15' | 'socialSecurity' | 'equipment10' | 'knowhow10' | 'patent10' | 'film11' | 'copyright12'


