/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayoutRequestPayee } from './payout-request-payee';
import { UserCompliance } from './user-compliance';
import { Wallet } from './wallet';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email'?: string;
    /**
     * 
     * @type {PayoutRequestPayee}
     * @memberof User
     */
    'phone_number'?: PayoutRequestPayee;
    /**
     * 
     * @type {Wallet}
     * @memberof User
     */
    'wallet'?: Wallet;
    /**
     * 
     * @type {UserCompliance}
     * @memberof User
     */
    'compliance'?: UserCompliance;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof User
     */
    'metadata'?: any;
}

