/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsersVerifyUserTokenRequest
 */
export interface UsersVerifyUserTokenRequest {
    /**
     * The token sent to the user.
     * @type {string}
     * @memberof UsersVerifyUserTokenRequest
     */
    'token': string;
}

