/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsersAddPayoutMethodRequest
 */
export interface UsersAddPayoutMethodRequest {
    /**
     * Payout platform to add.
     * @type {string}
     * @memberof UsersAddPayoutMethodRequest
     */
    'platform': UsersAddPayoutMethodRequestPlatformEnum;
    /**
     * Bank account or Cash App routing number. Required if `platform` = `ach` or `cash_app`.
     * @type {string}
     * @memberof UsersAddPayoutMethodRequest
     */
    'routing_number'?: string;
    /**
     * Bank account or Cash App account number. Required if `platform` = `ach` or `cash_app`.
     * @type {string}
     * @memberof UsersAddPayoutMethodRequest
     */
    'account_number'?: string;
    /**
     * Bank account type. Required if `platform` = `ach`.
     * @type {string}
     * @memberof UsersAddPayoutMethodRequest
     */
    'account_type'?: UsersAddPayoutMethodRequestAccountTypeEnum;
    /**
     * PayPal email address. Required if `platform` = `paypal`.
     * @type {string}
     * @memberof UsersAddPayoutMethodRequest
     */
    'email'?: string;
    /**
     * Venmo phone number. One of `phone_number` or `handle` is required if `platform` = `venmo`.
     * @type {string}
     * @memberof UsersAddPayoutMethodRequest
     */
    'phone_number'?: string;
    /**
     * Venmo handle. One of `phone_number` or `handle` is required if `platform` = `venmo`.
     * @type {string}
     * @memberof UsersAddPayoutMethodRequest
     */
    'handle'?: string;
    /**
     * Cash App Cash Tag. Required if `platform` = `cash_app`.
     * @type {string}
     * @memberof UsersAddPayoutMethodRequest
     */
    'cash_tag'?: string;
}

type UsersAddPayoutMethodRequestPlatformEnum = 'paypal' | 'venmo' | 'cash_app' | 'ach'
type UsersAddPayoutMethodRequestAccountTypeEnum = 'checking' | 'savings'


