/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsersCreateNewUserRequest
 */
export interface UsersCreateNewUserRequest {
    /**
     * The user\'s first name.
     * @type {string}
     * @memberof UsersCreateNewUserRequest
     */
    'first_name': string;
    /**
     * The user\'s last name.
     * @type {string}
     * @memberof UsersCreateNewUserRequest
     */
    'last_name': string;
    /**
     * The user\'s email address.
     * @type {string}
     * @memberof UsersCreateNewUserRequest
     */
    'email': string;
    /**
     * The user\'s phone number country code. e.g. \"1\"
     * @type {string}
     * @memberof UsersCreateNewUserRequest
     */
    'country_code': string;
    /**
     * The user\'s phone number. e.g. \"4157223331\".
     * @type {string}
     * @memberof UsersCreateNewUserRequest
     */
    'phone_number': string;
    /**
     * Username to assign the user.
     * @type {string}
     * @memberof UsersCreateNewUserRequest
     */
    'username'?: string;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     * @type {any}
     * @memberof UsersCreateNewUserRequest
     */
    'metadata'?: any;
}

