/*
dots api

Scalable and Flexible Payouts Infrastructure

The version of the OpenAPI document: 1.0
Contact: info@dots.dev

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Wallet
 */
export interface Wallet {
    /**
     * 
     * @type {number}
     * @memberof Wallet
     */
    'amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof Wallet
     */
    'withdrawable_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof Wallet
     */
    'credit_balance'?: number;
}

